[package]
name = "cargo-mobile-runner"
version = "0.1.0"
authors = ["Wanway Song <sww4718168@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
